# 开发环境配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ai_doc_engine?currentSchema=public
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public

  mail:
    host: smtp.qq.com
    port: 465
    username: 2219746581@qq.com
    password: kaztvuiusvvhdjhj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true



# 开发环境日志级别
logging:
  level:
    root: INFO
    com.aidoc.engine: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

# 开发环境前端地址
app:
  frontend-url: http://localhost:3514

# JWT 配置
jwt:
  secret: ai-doc-engine-secret-key-for-jwt-token-generation-must-be-at-least-256-bits
  expiration: 604800000  # 7 天（毫秒）

# 一站式服务大厅 OAuth2 配置（后续把这3个填上即可）
oauth:
  client-id: test
  client-secret: test
  redirect-uri: http://localhost:8687/oauth/callback
  auth-host: https://ywtb.gznc.edu.cn/center-auth-server
  request-timeout-millis: 10000
